Add as_point_non_managing_staff. Refactoring the code.
Yakov-Varnaev/bbq pull request #19
Opened 2023-12-29 16:13 UTC by platsajacki

2023-12-29 19:14 UTC, Yakov-Varnaev approved these changes

2023-12-29 19:40 UTC, Yakov-Varnaev requested changes

2023-12-29 19:40 UTC, Yakov-Varnaev commented on src/companies/tests/conftest.py
> +def user_fixtures_collection(as_another_company_owner, as_user, as_anon) -> dict[str, Callable]:
Let's annotate every client. And also return value is `dict[str, ApiClient]`.

2023-12-29 19:40 UTC, Yakov-Varnaev commented on src/companies/tests/conftest.py
> +def as_point_non_managing_staff(request, user_fixtures_collection) -> ApiClient:
user_fixtures_collection also should be annotated

2023-12-30 06:42 UTC, platsajacki commented
Pay attention to the import `from _pytest.fixtures import FixtureRequest`. Can we do this for a proper annotation?

2023-12-30 08:47 UTC, Yakov-Varnaev commented
> Pay attention to the import `from _pytest.fixtures import FixtureRequest`. Can we do this for a proper annotation?

@platsajacki yeah, sure

2023-12-30 08:51 UTC, Yakov-Varnaev requested changes

2023-12-30 08:51 UTC, Yakov-Varnaev commented on src/companies/tests/conftest.py
> +from _pytest.fixtures import FixtureRequest  # noqa: I001
```suggestion
from pytest import FixtureRequest
```

2023-12-30 08:51 UTC, Yakov-Varnaev commented on src/companies/tests/test_stock_viewset.py
> +        expected_status=as_point_non_managing_staff.expected_status,  # type: ignore[attr-defined]
It's better to create separate class to make proper annotation

2023-12-30 13:32 UTC, platsajacki commented on src/companies/tests/conftest.py
> +from _pytest.fixtures import FixtureRequest  # noqa: I001
I had to use # noqa: PT013.

2024-01-02 15:49 UTC, Yakov-Varnaev requested changes
Final changes I suppose

2024-01-02 15:49 UTC, Yakov-Varnaev commented on src/companies/tests/conftest.py
> +    return client  # type: ignore[return-value]
This will allow us to remove mypy ignore statements
```suggestion
    user, status = request.param
    client: ApiClient = user_fixtures_collection[user]
    statused_client = StatusedClient(status, getattr(client, "user", None)
    return statused_client
```

2024-01-03 07:51 UTC, platsajacki commented on src/companies/tests/conftest.py
> +    return client  # type: ignore[return-value]
Then we raise in the tests: `sqlite3.IntegrityError: UNIQUE constraint failed: authtoken_token.user_id`. I will try to do a new token for StatusApiClient.

2024-01-03 10:57 UTC, Yakov-Varnaev approved these changes

2024-01-03 11:01 UTC, merged