#20 CRUD for MaterialType
Yakov-Varnaev/bbq pull request #22
Opened 2024-01-08 14:54 UTC by platsajacki

Add CRUD for MaterialType. I made the LowercaseCharField field ([exemple](https://github.com/Hipo/drf-extra-fields/blob/8c18a7542c8a38fe3dccd1874a74a38410aa3a7f/drf_extra_fields/fields.py#L307)), which allows you to do with a single serializer.

2024-01-10 21:00 UTC, Yakov-Varnaev requested changes

2024-01-10 21:00 UTC, Yakov-Varnaev commented on src/app/api/permissions.py
> +        return bool(request.user and request.user.is_superuser)
1. bool is useless there
2. It's better to check that user is authenticated

```suggestion
        return request.user.is_authenticated and request.user.is_superuser
```

2024-01-10 21:00 UTC, Yakov-Varnaev commented on src/app/api/permissions.py
> +        return bool(request.method in permissions.SAFE_METHODS or request.method == "POST")
```suggestion
        return request.method in permissions.SAFE_METHODS + ["POST"]
```

2024-01-10 21:00 UTC, Yakov-Varnaev commented on src/companies/api/fields.py
> +        return value.lower()
```suggestion
        return super().to_internal_value(data).lower()
```

2024-01-10 21:00 UTC, Yakov-Varnaev commented on src/companies/api/fields.py
> +        data: str = super().to_representation(value)
Same here

2024-01-10 21:00 UTC, Yakov-Varnaev commented on src/companies/api/fields.py
> +class LowercaseCharField(CharField):
Also make sure that this field ignores whitespaces.

2024-01-10 21:00 UTC, Yakov-Varnaev commented on src/companies/api/serializers/stock.py
> +    """The "name" field converts to lowercase during serialization and deserialization."""
Quite obvious from field name
```suggestion
```

2024-01-10 21:00 UTC, Yakov-Varnaev commented on src/companies/factory/stock.py
> +def material_type(self: FixtureFactory, **kwargs: dict) -> dict:
Wrong annotation

```suggestion
def material_type(self: FixtureFactory, **kwargs: dict) -> MaterialType:
```

2024-01-10 21:00 UTC, Yakov-Varnaev commented on src/companies/factory/stock.py
> +            "name": self.field("name"),
name refers to human name, word is a better option I think

```suggestion
            "name": self.field("word"),
```

2024-01-10 21:00 UTC, Yakov-Varnaev commented on src/companies/services/stock/material_type_creator.py
> +        return MaterialType.objects.get_or_create(name=self.serializer.validated_data["name"])[0]
It would be nice to add logging here. sth like "material <name> was created" or "material <name> already exists".

2024-01-10 21:00 UTC, Yakov-Varnaev commented on src/companies/tests/services/test_material_type_creator.py
> +def test_material_type_do_not_duplicate(material_type_data: dict):
```suggestion
def test_material_type_does_not_duplicate(material_type_data: dict):
```

2024-01-10 21:00 UTC, Yakov-Varnaev commented on src/companies/tests/test_material_type_viewset.py
> +def test_company_create_invalid_data(
Seems like the name of the test is wrong.

2024-01-10 21:00 UTC, Yakov-Varnaev commented on src/companies/tests/test_material_type_viewset.py
> +    for request in [as_superuser.put, as_superuser.patch]:
patch is useless in this case, so we can remove it.

2024-01-10 21:00 UTC, Yakov-Varnaev commented on src/companies/tests/test_material_type_viewset.py
> +def test_udpate_material_type(
test_superuser_can_update_material_type*

2024-01-10 21:00 UTC, Yakov-Varnaev commented on src/companies/tests/test_material_type_viewset.py
> +        (lf("as_superuser"), status.HTTP_200_OK),
superuser shouldn't be there

2024-01-10 21:00 UTC, Yakov-Varnaev commented on src/companies/tests/test_material_type_viewset.py
> +    expected_data = MaterialTypeSerializer(material_type).data
```suggestion
```

2024-01-10 21:00 UTC, Yakov-Varnaev commented on src/companies/tests/test_material_type_viewset.py
> +        assert MaterialTypeSerializer(material_type).data == expected_data
```suggestion
    response = request(url, data=factory.material_type_data(**invalid_fields), expected_status=status.HTTP_400_BAD_REQUEST)  # type: ignore

    assert MaterialTypeSerializer(material_type).data == response
```

2024-01-10 21:00 UTC, Yakov-Varnaev commented on src/companies/api/fields.py
> +class LowercaseCharField(CharField):
I don't see any unit tests for this field.

2024-01-10 21:00 UTC, Yakov-Varnaev commented on src/companies/api/viewsets/stock.py
> +    def perform_create(self, serializer: BaseSerializer[MaterialTypeSerializer]) -> None:
```suggestion
    def perform_create(self, serializer: BaseSerializer[MaterialType]) -> None:
```

2024-01-10 21:00 UTC, Yakov-Varnaev commented on src/companies/api/viewsets/stock.py
> +@extend_schema(tags=["types-of-materials"])
```suggestion
@extend_schema(tags=["material-types"])
```

2024-01-10 21:00 UTC, Yakov-Varnaev commented on src/companies/urls.py
> +router.register("types-of-materials", viewsets.MaterialTypeViewSet, basename="types-of-materials")
`material-types` would be better

2024-01-11 05:52 UTC, platsajacki commented on src/companies/api/viewsets/stock.py
> +    def perform_create(self, serializer: BaseSerializer[MaterialTypeSerializer]) -> None:
MyPy raises the error: `error: Argument 1 to "MaterialTypeCreator" has incompatible type "BaseSerializer[MaterialType]"; expected "BaseSerializer[MaterialTypeSerializer]"  [arg-type]`

2024-01-11 06:54 UTC, platsajacki commented on src/companies/tests/test_material_type_viewset.py
> +        assert MaterialTypeSerializer(material_type).data == expected_data
It shouldn't be equality, because response returns `{'name': ['This field may not be blank.']}`. We can check the status_code, but I would check the integrity of the data.

2024-01-12 11:48 UTC, Yakov-Varnaev commented on src/companies/api/viewsets/stock.py
> +    def perform_create(self, serializer: BaseSerializer[MaterialTypeSerializer]) -> None:
Oh, ok

2024-01-12 11:50 UTC, Yakov-Varnaev commented on src/companies/tests/test_material_type_viewset.py
> +        assert MaterialTypeSerializer(material_type).data == expected_data
Then we have to check that we got expected response.

2024-01-12 11:56 UTC, Yakov-Varnaev requested changes

2024-01-12 11:56 UTC, Yakov-Varnaev commented on src/app/conf/logging.py
> +LOGGING = {
Do, we really need it now?

2024-01-12 11:56 UTC, Yakov-Varnaev commented on src/companies/services/stock/material_type_creator.py
> +        self.logger = logging.getLogger(__name__)
This have to be initiated on the module level

logger = logging.getLogger(__name__)

```suggestion


class MaterialTypeCreator(BaseService):
    def __init__(self, serializer: BaseSerializer[MaterialTypeSerializer]) -> None:
        self.serializer = serializer
```

2024-01-12 11:56 UTC, Yakov-Varnaev commented on src/companies/services/stock/material_type_creator.py
> +        return material_type
```suggestion
        msg = <...> if created else <...>
        logger.info(msg, ...)
        return material_type
```

2024-01-12 11:56 UTC, Yakov-Varnaev commented on src/companies/tests/test_fields.py
> +    internal_value = lowercase_char_field.to_internal_value(input_value)
One time variables are bad, lets remove them

2024-01-12 11:56 UTC, Yakov-Varnaev commented on src/companies/tests/test_material_type_viewset.py
> +    url: str = reverse("api_v1:companies:material-types-list")
This annotations are useless, lets remove them.

2024-01-12 11:57 UTC, Yakov-Varnaev requested changes

2024-01-12 11:57 UTC, Yakov-Varnaev commented on src/companies/services/stock/material_type_creator.py
> +    def __init__(self, serializer: BaseSerializer[MaterialTypeSerializer]) -> None:
?
```suggestion
    def __init__(self, serializer: MaterialTypeSerializer) -> None:
```

2024-01-13 12:04 UTC, platsajacki commented on src/companies/services/stock/material_type_creator.py
> +    def __init__(self, serializer: BaseSerializer[MaterialTypeSerializer]) -> None:
I tried to do it.
`error: Argument 1 to "MaterialTypeCreator" has incompatible type "BaseSerializer[MaterialTypeSerializer]"; expected "MaterialTypeSerializer"  [arg-type]`

2024-01-13 15:05 UTC, Yakov-Varnaev requested changes

2024-01-13 15:05 UTC, Yakov-Varnaev commented on src/companies/tests/test_material_type_viewset.py
> +def test_authorized_user_cannot_create_material_type(
Пользователь должен уметь создавать тип материала.

2024-01-13 15:05 UTC, Yakov-Varnaev commented on src/companies/tests/test_material_type_viewset.py
> +def test_can_update_only_superuser(
```suggestion
def terst_unauthorized_users_cannot_update_material_type(
```

2024-01-13 15:05 UTC, Yakov-Varnaev commented on src/companies/tests/test_material_type_viewset.py
> +def test_can_delete_only_superuser(client: ApiClient, expected_status: int, material_type: MaterialType):
```suggestion
def test_only_super_user_can_delete_material_type(client: ApiClient, expected_status: int, material_type: MaterialType):
```

2024-01-13 15:06 UTC, Yakov-Varnaev commented on src/companies/tests/test_material_type_viewset.py
> +def test_authorized_user_cannot_create_material_type(
```suggestion
def test_authenticated_user_can_create_material_type(
```

2024-01-13 15:07 UTC, Yakov-Varnaev approved these changes

2024-01-13 15:50 UTC, merged