#24
Yakov-Varnaev/bbq pull request #31
Opened 2024-01-29 08:19 UTC by platsajacki

2024-01-30 19:11 UTC, Yakov-Varnaev requested changes

2024-01-30 19:11 UTC, Yakov-Varnaev commented on src/companies/api/serializers/employee.py
> +            "archived",
Usually we don't really want to show this flag, so let's hide it.

2024-01-30 19:11 UTC, Yakov-Varnaev commented on src/companies/api/serializers/employee.py
> +                fields=["procedure", "employee"],
There can be more than one master procedures(archived and non archived), so we shouldn't limit this.

2024-01-30 19:11 UTC, Yakov-Varnaev commented on src/companies/api/serializers/employee.py
> +        data["procedure"] = {
Nested serialization doesn't work this way.

https://www.django-rest-framework.org/api-guide/serializers/#dealing-with-nested-objects

2024-01-30 19:11 UTC, Yakov-Varnaev commented on src/companies/tests/test_master_procedure_viewset.py
> +        expected_status=status.HTTP_201_CREATED,
This is the default expected status for post requests, so we can omit this.

2024-01-30 19:11 UTC, Yakov-Varnaev commented on src/companies/tests/test_master_procedure_viewset.py
> +    response = as_point_managing_staff.post(reverse("api_v1:companies:master-procedure-list", kwargs=master_procedure_reverse_kwargs), master_procedure_data)  # type: ignore[no-untyped-call]
Looks to long, lets put url into variable.

2024-01-30 19:11 UTC, Yakov-Varnaev commented on src/companies/tests/test_master_procedure_viewset.py
> +    as_point_managing_staff.post(  # type: ignore[no-untyped-call]
use a fixture instead of two calls.

2024-01-30 19:11 UTC, Yakov-Varnaev commented on src/companies/tests/test_master_procedure_viewset.py
> +    assert not MasterProcedure.include_archived.filter(archived=timezone.now()).exists()
Current check doesn't guarantee that master procedure was not deleted at all, it's better to check existance this way.

```suggestion
    assert MasterProcedure.include_archived.filter(id=master_procedure.id).exists()
```

2024-01-30 19:11 UTC, Yakov-Varnaev commented on src/companies/tests/test_master_procedure_viewset.py
> +def test_master_procedure_can_restore(
```suggestion
def test_master_procedure_can_be_restored(
```

2024-01-30 19:11 UTC, Yakov-Varnaev commented on src/companies/tests/test_master_procedure_viewset.py
> +    assert_exists(MasterProcedure)
we can call refresh_from_db and check that archived flag is None, it would be a better approach here.

2024-01-30 19:45 UTC, platsajacki commented on src/companies/api/serializers/employee.py
> +                fields=["procedure", "employee"],
There are no archived objects in the `MasterProcedure.objects.all()` request. `objects = ArchiveDeletedManager()`. Therefore I think, it's not necessary to delete it.

2024-01-31 06:59 UTC, Yakov-Varnaev commented on src/companies/api/serializers/employee.py
> +                fields=["procedure", "employee"],
Im dumb, dont listen to this comment :)))

2024-01-31 07:53 UTC, Yakov-Varnaev requested changes

2024-01-31 07:53 UTC, Yakov-Varnaev commented on src/companies/tests/test_master_procedure_viewset.py
> +    assert MasterProcedure.include_archived.filter(id=master_procedure.id).exists()
This is redundant, we checked this on the previous line.

2024-01-31 07:53 UTC, Yakov-Varnaev commented on src/companies/tests/test_master_procedure_viewset.py
> +    archived_master_procedure = MasterProcedure.include_archived.get(id=master_procedure.id)
Create `archived_master_procedure` fixture and use separate file for this test as it actually not a part of API.

2024-01-31 08:35 UTC, Yakov-Varnaev approved these changes

2024-01-31 08:36 UTC, merged